theme: jekyll-theme-cayman
title: "Statistics: Coping with Uncertainty"
description: "Companion materials (datasets, code, and updates) for the book<br>by <em>Göran Kauermann, Giacomo De Nicola, Cornelius Fritz, and David Rügamer</em>"
show_downloads: false
