theme: jekyll-theme-cayman
title: "Statistics: Coping with Uncertainty"
description: "Companion materials (datasets, code, and updates) for the book by<br>Göran Kauermann, Giacomo De Nicola, Cornelius Fritz, and David Rügamer"
show_downloads: false